//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES_RESTAURANTE : PERSONAS
    {
        public CLIENTES_RESTAURANTE()
        {
            this.ORDENES = new HashSet<ORDENES>();
            this.VALORACIONES = new HashSet<VALORACIONES>();
        }
    
    
        public virtual ICollection<ORDENES> ORDENES { get; set; }
        public virtual ICollection<VALORACIONES> VALORACIONES { get; set; }
    }
}
