//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRIBUIDORES
    {
        public DISTRIBUIDORES()
        {
            this.ACOMPANANTES = new HashSet<ACOMPANANTES>();
            this.INGREDIENTES = new HashSet<INGREDIENTES>();
        }
    
        public decimal CODIGODISTRIBUIDOR { get; set; }
        public string NOMBRE { get; set; }
        public string RNC { get; set; }
    
        public virtual ICollection<ACOMPANANTES> ACOMPANANTES { get; set; }
        public virtual ICollection<INGREDIENTES> INGREDIENTES { get; set; }
    }
}
