//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOS : PERSONAS
    {
        public EMPLEADOS()
        {
            this.ORDENES = new HashSet<ORDENES>();
            this.ORDENESEMPLEADOPLATOS = new HashSet<ORDENESEMPLEADOPLATOS>();
        }
    
        public Nullable<decimal> SEXO { get; set; }
        public Nullable<decimal> CARGO { get; set; }
    
        public virtual CARGOS CARGOS { get; set; }
        public virtual SEXOS SEXOS { get; set; }
        public virtual ICollection<ORDENES> ORDENES { get; set; }
        public virtual ICollection<ORDENESEMPLEADOPLATOS> ORDENESEMPLEADOPLATOS { get; set; }
    }
}
