//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURAS
    {
        public decimal CODIGOFACTURA { get; set; }
        public Nullable<decimal> ORDEN { get; set; }
        public Nullable<decimal> TIPOPAGO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> HORA { get; set; }
        public Nullable<decimal> MINUTO { get; set; }
        public Nullable<decimal> SEGUNDO { get; set; }
    
        public virtual ORDENES ORDENES { get; set; }
        public virtual TIPOSPAGOS TIPOSPAGOS { get; set; }
    }
}
