//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPUESTOS_RESTAURANTE
    {
        public IMPUESTOS_RESTAURANTE()
        {
            this.OBJETOS = new HashSet<OBJETOS>();
        }
    
        public decimal CODIGOIMPUESTO { get; set; }
        public Nullable<decimal> TARIFA { get; set; }
    
        public virtual ICollection<OBJETOS> OBJETOS { get; set; }
    }
}
