//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIOS
    {
        public INVENTARIOS()
        {
            this.OBJETOSINVENTARIOS = new HashSet<OBJETOSINVENTARIOS>();
        }
    
        public decimal CODIGOINVENTARIO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<OBJETOSINVENTARIOS> OBJETOSINVENTARIOS { get; set; }
    }
}
