//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENUS
    {
        public MENUS()
        {
            this.PLATOSMENUS = new HashSet<PLATOSMENUS>();
            this.ACOMPANANTES = new HashSet<ACOMPANANTES>();
        }
    
        public decimal CODIGOMENU { get; set; }
    
        public virtual ICollection<PLATOSMENUS> PLATOSMENUS { get; set; }
        public virtual ICollection<ACOMPANANTES> ACOMPANANTES { get; set; }
    }
}
