//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaModelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CARGOS> CARGOS { get; set; }
        public DbSet<DISTRIBUIDORES> DISTRIBUIDORES { get; set; }
        public DbSet<ESTADOORDENES> ESTADOORDENES { get; set; }
        public DbSet<FACTURAS> FACTURAS { get; set; }
        public DbSet<IMPUESTOS_RESTAURANTE> IMPUESTOS_RESTAURANTE { get; set; }
        public DbSet<INVENTARIOS> INVENTARIOS { get; set; }
        public DbSet<MENUS> MENUS { get; set; }
        public DbSet<MESAS> MESAS { get; set; }
        public DbSet<OBJETOS> OBJETOS { get; set; }
        public DbSet<OBJETOSINVENTARIOS> OBJETOSINVENTARIOS { get; set; }
        public DbSet<ORDENES> ORDENES { get; set; }
        public DbSet<ORDENESEMPLEADOPLATOS> ORDENESEMPLEADOPLATOS { get; set; }
        public DbSet<ORDENESPLATOS> ORDENESPLATOS { get; set; }
        public DbSet<PERSONAS> PERSONAS { get; set; }
        public DbSet<PLATOSMENUS> PLATOSMENUS { get; set; }
        public DbSet<RECETAS> RECETAS { get; set; }
        public DbSet<RECETASINGREDIENTES> RECETASINGREDIENTES { get; set; }
        public DbSet<SEXOS> SEXOS { get; set; }
        public DbSet<TIPOSPAGOS> TIPOSPAGOS { get; set; }
        public DbSet<UNIDADES> UNIDADES { get; set; }
        public DbSet<VALORACIONES> VALORACIONES { get; set; }
    }
}
