//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJETOS
    {
        public OBJETOS()
        {
            this.OBJETOSINVENTARIOS = new HashSet<OBJETOSINVENTARIOS>();
            this.IMPUESTOS_RESTAURANTE = new HashSet<IMPUESTOS_RESTAURANTE>();
        }
    
        public decimal CODIGOOBJETO { get; set; }
    
        public virtual ICollection<OBJETOSINVENTARIOS> OBJETOSINVENTARIOS { get; set; }
        public virtual ICollection<IMPUESTOS_RESTAURANTE> IMPUESTOS_RESTAURANTE { get; set; }
    }
}
