//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJETOSINVENTARIOS
    {
        public decimal OBJETO { get; set; }
        public decimal INVENTARIO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<decimal> UNIDADES { get; set; }
    
        public virtual INVENTARIOS INVENTARIOS { get; set; }
        public virtual OBJETOS OBJETOS { get; set; }
    }
}
