//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDENESPLATOS
    {
        public decimal ORDEN { get; set; }
        public decimal PLATO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
    
        public virtual ORDENES ORDENES { get; set; }
        public virtual PLATOS PLATOS { get; set; }
    }
}
