//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLATOS : OBJETOS
    {
        public PLATOS()
        {
            this.ORDENESEMPLEADOPLATOS = new HashSet<ORDENESEMPLEADOPLATOS>();
            this.ORDENESPLATOS = new HashSet<ORDENESPLATOS>();
            this.PLATOSMENUS = new HashSet<PLATOSMENUS>();
            this.RECETAS = new HashSet<RECETAS>();
            this.VALORACIONES = new HashSet<VALORACIONES>();
        }
    
        public string NOMBRE { get; set; }
        public Nullable<decimal> COSTOMANOFACTURA { get; set; }
    
        public virtual ICollection<ORDENESEMPLEADOPLATOS> ORDENESEMPLEADOPLATOS { get; set; }
        public virtual ICollection<ORDENESPLATOS> ORDENESPLATOS { get; set; }
        public virtual ICollection<PLATOSMENUS> PLATOSMENUS { get; set; }
        public virtual ICollection<RECETAS> RECETAS { get; set; }
        public virtual ICollection<VALORACIONES> VALORACIONES { get; set; }
    }
}
