//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETASINGREDIENTES
    {
        public decimal RECETA { get; set; }
        public decimal INGREDIENTE { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<decimal> UNIDAD { get; set; }
    
        public virtual INGREDIENTES INGREDIENTES { get; set; }
        public virtual RECETAS RECETAS { get; set; }
        public virtual UNIDADES UNIDADES { get; set; }
    }
}
