//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALORACIONES
    {
        public VALORACIONES()
        {
            this.PLATOS = new HashSet<PLATOS>();
        }
    
        public decimal CODIGOVALORACION { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> CLIENTE { get; set; }
        public Nullable<decimal> NUMERO { get; set; }
    
        public virtual CLIENTES_RESTAURANTE CLIENTES_RESTAURANTE { get; set; }
        public virtual ICollection<PLATOS> PLATOS { get; set; }
    }
}
